### ISSUE TITLE
Can't import a given Spotify playlist

### ISSUE THREAD

**Issue by GeiserX** [xaviqo/SoulSyncBot#2]
First of all, thanks for this great piece of software, @xaviqo 

However, I'm struggling in the following points:

- First, trying to incorporate [a given playlist](https://open.spotify.com/playlist/07sNNK4UXXcI3gyWDeMuiH?si=98c22d709ed744fc) is not working. There's an error: 
```
2024-02-24 23:09:35 be     | 2024-02-24 22:09:35,382        ERROR [http-nio-14947-exec-10] ache.juli.logging.DirectJDKLog: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0] with root cause
2024-02-24 23:09:35 be     | java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
...
``` 
This is the playlist I'm really looking forward to. I don't care about the rest

- But if I try with others, it's working. However, `slskd` does not seem to work, so it's not downloading anything. Checking on http://localhost:5030 seems like the soulseek user isn't configured, but if I configure it in the yaml values files, it won't connect. I'm using the[ bundled slskd](https://github.com/xaviqo/SoulSyncBot/blob/master/DOCKER/docker-compose.yml#L38). Given that this software is heavily relying on it, I would suggest on having an annex or something similar, explaining the basic setup, as most people would not even know about what it is doing.

PS: [Original issue](https://www.reddit.com/r/Soulseek/comments/1az49j7/convert_mp3_folder_into_flac/) I'm trying to address.

**Comment by GeiserX** [comment]
I managed to get `slskd` working, it was simply wrong credentials. But anyway, I guess this repo could highly benefit from a short piece of docs on `slskd`.

**Comment by GeiserX** [comment]
If you need the full log:

```
be     | 2024-02-25 12:21:48,001        ERROR [http-nio-14947-exec-10] .xavi.soulsync.gateway.Gateway: [ SPOTIFY | getToken ] - (JsonProcessingException) URL: https://api.spotify.com/v1/playlists/{playlistId}/images - An error occurred while deserializing the JSON response from SPOTIFY API - Message: Cannot deserialize value of type `[Ltech.xavi.soulsync.dto.gateway.spotify.SpotifyPlaylistCover;` from Object value (token `JsonToken.START_OBJECT`)
be     |  at [Source: (String)"{
be     |   "error": {
be     |     "status": 401,
be     |     "message": "No token provided"
be     |   }
be     | }"; line: 1, column: 1]
be     | com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `[Ltech.xavi.soulsync.dto.gateway.spotify.SpotifyPlaylistCover;` from Object value (token `JsonToken.START_OBJECT`)
be     |  at [Source: (String)"{
be     |   "error": {
be     |     "status": 401,
be     |     "message": "No token provided"
be     |   }
be     | }"; line: 1, column: 1]
be     |        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
be     |        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1752)
be     |        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1526)
be     |        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1473)
be     |        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.handleNonArray(ObjectArrayDeserializer.java:345)
be     |        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
be     |        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:26)
be     |        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
be     |        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
be     |        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
be     |        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
be     |        at tech.xavi.soulsync.gateway.Gateway.mapResponseBody(Gateway.java:42)
be     |        at tech.xavi.soulsync.gateway.Gateway.callMapped(Gateway.java:32)
be     |        at tech.xavi.soulsync.gateway.SpotifyGateway.getPlaylistCover(SpotifyGateway.java:96)
be     |        at tech.xavi.soulsync.service.main.PlaylistService.getCover(PlaylistService.java:170)
be     |        at tech.xavi.soulsync.service.main.PlaylistService.savePlaylist(PlaylistService.java:41)
be     |        at tech.xavi.soulsync.service.rest.PlaylistTypeSaverService.handlePlaylistRequest(PlaylistTypeSaverService.java:40)
be     |        at tech.xavi.soulsync.service.rest.PlaylistTypeSaverService.handleUserRequest(PlaylistTypeSaverService.java:33)
be     |        at tech.xavi.soulsync.service.rest.PlaylistRestService.addPlaylistRequest(PlaylistRestService.java:39)
be     |        at tech.xavi.soulsync.rest.PlaylistController.addPlaylist(PlaylistController.java:36)
be     |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
be     |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
be     |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
be     |        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
be     |        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
be     |        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
be     |        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
be     |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
be     |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
be     |        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
be     |        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
be     |        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
be     |        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
be     |        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
be     |        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
be     |        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
be     |        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at tech.xavi.soulsync.configuration.security.filters.JwtAuthFilter.doFilterInternal(JwtAuthFilter.java:37)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365)
be     |        at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
be     |        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
be     |        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
be     |        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
be     |        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)      
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
be     |        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
be     |        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
be     |        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
be     |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
be     |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
be     |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
be     |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
be     |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
be     |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
be     |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
be     |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
be     |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
be     |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740)
be     |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
be     |        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
be     |        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
be     |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
be     |        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by GeiserX** [comment]
FYI: This is the full error message
```
be     | 2024-02-25 12:24:12,856        ERROR [http-nio-14947-exec-6] ache.juli.logging.DirectJDKLog: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0] with root cause
be     | java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
be     |        at tech.xavi.soulsync.service.main.PlaylistService.getCover(PlaylistService.java:170)
be     |        at tech.xavi.soulsync.service.main.PlaylistService.savePlaylist(PlaylistService.java:41)
be     |        at tech.xavi.soulsync.service.rest.PlaylistTypeSaverService.handlePlaylistRequest(PlaylistTypeSaverService.java:40)
be     |        at tech.xavi.soulsync.service.rest.PlaylistTypeSaverService.handleUserRequest(PlaylistTypeSaverService.java:33)
be     |        at tech.xavi.soulsync.service.rest.PlaylistRestService.addPlaylistRequest(PlaylistRestService.java:39)
be     |        at tech.xavi.soulsync.rest.PlaylistController.addPlaylist(PlaylistController.java:36)
be     |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
be     |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
be     |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
be     |        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
be     |        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
be     |        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
be     |        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
be     |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
be     |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
be     |        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
be     |        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
be     |        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
be     |        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
be     |        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
be     |        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
be     |        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
be     |        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at tech.xavi.soulsync.configuration.security.filters.JwtAuthFilter.doFilterInternal(JwtAuthFilter.java:37)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365)
be     |        at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
be     |        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
be     |        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
be     |        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
be     |        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)      
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
be     |        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
be     |        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
be     |        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
be     |        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
be     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
be     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
be     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
be     |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
be     |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
be     |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
be     |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
be     |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
be     |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
be     |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
be     |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
be     |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
be     |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
be     |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740)
be     |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
be     |        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
be     |        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
be     |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
be     |        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by xaviqo** [comment]
Hi @GeiserX, thank you very much for your report! 

About the error you comment I will check with the same playlist in my local, to see if I can help and fix the problem.

The issue of documentation with slskd you are absolutely right and it is something I want to do, as I imagine that many people are not slskd users and maybe they are not able to get the bot working. 

I try to give you an answer asap!

**Comment by xaviqo** [comment]
Hi again! Is it possible that this playlist is in private status or something? 

I have encountered two problems. One is that the Spotify Songs arrive without the unique ID that they give them, another is that it did not contemplate playlists without cover. 

Anyway, I have made a workaround to solve this. I will upload a new version with this. 

Thank you very much for the report! I hope I'll be able to dedicate some time to this project again :)

![image](https://github.com/xaviqo/SoulSyncBot/assets/82182761/32895cc8-2101-4685-a392-14342d1e4e67)
