### ISSUE TITLE
Can't login to the Bot

### ISSUE THREAD

**Issue by RandomLegend** [xaviqo/SoulSyncBot#3]
![image](https://github.com/xaviqo/SoulSyncBot/assets/38812603/274ae39d-048d-4915-9fa8-4fb93744d083)

After building the docker image and opening the adress i can't login and get this error.

Backend logs:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.4)

2024-04-16 08:08:18,748        INFO [main] amework.boot.StartupInfoLogger: Starting SoulSyncApplication v0.2.0-Beta using Java 17-ea with PID 1 (/app/app.jar started by root in /app)
2024-04-16 08:08:18,759        INFO [main] amework.boot.SpringApplication: No active profile set, falling back to 1 default profile: "default"
2024-04-16 08:08:19,686        INFO [main] epositoryConfigurationDelegate: Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-04-16 08:08:19,780        INFO [main] epositoryConfigurationDelegate: Finished Spring Data repository scanning in 76 ms. Found 3 JPA repository interfaces.
2024-04-16 08:08:20,540        INFO [main] mbedded.tomcat.TomcatWebServer: Tomcat initialized with port(s): 6743 (http)
2024-04-16 08:08:20,551        INFO [main] ache.juli.logging.DirectJDKLog: Initializing ProtocolHandler ["http-nio-6743"]
2024-04-16 08:08:20,555        INFO [main] ache.juli.logging.DirectJDKLog: Starting service [Tomcat]
2024-04-16 08:08:20,556        INFO [main] ache.juli.logging.DirectJDKLog: Starting Servlet engine: [Apache Tomcat/10.1.13]
2024-04-16 08:08:20,648        INFO [main] ache.juli.logging.DirectJDKLog: Initializing Spring embedded WebApplicationContext
2024-04-16 08:08:20,650        INFO [main] letWebServerApplicationContext: Root WebApplicationContext: initialization completed in 1836 ms
2024-04-16 08:08:20,884        INFO [main] te.jpa.internal.util.LogHelper: HHH000204: Processing PersistenceUnitInfo [name: default]
2024-04-16 08:08:21,003        INFO [main] org.hibernate.Version         : HHH000412: Hibernate ORM core version 6.2.9.Final
2024-04-16 08:08:21,007        INFO [main] org.hibernate.cfg.Environment : HHH000406: Using bytecode reflection optimizer
2024-04-16 08:08:21,247        INFO [main] rnal.BytecodeProviderInitiator: HHH000021: Bytecode provider name : bytebuddy
2024-04-16 08:08:21,469        INFO [main] unit.SpringPersistenceUnitInfo: No LoadTimeWeaver setup: ignoring JPA class transformer
2024-04-16 08:08:21,500        INFO [main] zaxxer.hikari.HikariDataSource: HikariPool-1 - Starting...
2024-04-16 08:08:21,742        INFO [main] .zaxxer.hikari.pool.HikariPool: HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@3b08f438
2024-04-16 08:08:21,745        INFO [main] zaxxer.hikari.HikariDataSource: HikariPool-1 - Start completed.
2024-04-16 08:08:22,227        INFO [main] rnal.BytecodeProviderInitiator: HHH000021: Bytecode provider name : bytebuddy
2024-04-16 08:08:23,234        INFO [main] .internal.JtaPlatformInitiator: HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2024-04-16 08:08:23,322        INFO [main] stractEntityManagerFactoryBean: Initialized JPA EntityManagerFactory for persistence unit 'default'
2024-04-16 08:08:24,235        INFO [main] ory.query.QueryEnhancerFactory: Hibernate is in classpath; If applicable, HQL parser will be used.
2024-04-16 08:08:24,828        INFO [main] epository.JsonBackupRepository: New directory has been created: /app/db
2024-04-16 08:08:24,828        INFO [main] epository.JsonBackupRepository: New file has been created: /app/db/cfg.json
2024-04-16 08:08:24,829        INFO [main] epository.JsonBackupRepository: File cfg.json is empty, no data to load
2024-04-16 08:08:24,886        INFO [main] ce.config.ConfigurationService: JSON configuration file not found. Loaded default values from properties
2024-04-16 08:08:24,963        ERROR [scheduling-1] .xavi.soulsync.gateway.Gateway: [ SLSKD | getToken ] - (UnirestException) URL: http://localhost:5030/api/v0/session - An error occurred getting a response from the SLSKD API - Message: org.apache.http.conn.HttpHostConnectException: Connect to localhost:5030 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
com.mashape.unirest.http.exceptions.UnirestException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:5030 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
	at tech.xavi.soulsync.gateway.Gateway.getResponse(Gateway.java:67)
	at tech.xavi.soulsync.gateway.Gateway.call(Gateway.java:55)
	at tech.xavi.soulsync.gateway.Gateway.callMapped(Gateway.java:35)
	at tech.xavi.soulsync.gateway.SlskdGateway.getToken(SlskdGateway.java:138)
	at tech.xavi.soulsync.service.auth.AuthService.getSlskdToken(AuthService.java:50)
	at tech.xavi.soulsync.service.task.DownloadService.findStuckDownloads(DownloadService.java:76)
	at tech.xavi.soulsync.service.task.TaskManagerService.runScheduledTask(TaskManagerService.java:58)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:5030 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
	... 15 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:669)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:331)
	at java.base/java.net.Socket.connect(Socket.java:630)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 26 more
2024-04-16 08:08:24,969        ERROR [scheduling-1] .TaskUtils$LoggingErrorHandler: Unexpected error occurred in scheduled task
tech.xavi.soulsync.configuration.security.SoulSyncException
	at tech.xavi.soulsync.gateway.Gateway.handleUnirestException(Gateway.java:125)
	at tech.xavi.soulsync.gateway.Gateway.call(Gateway.java:57)
	at tech.xavi.soulsync.gateway.Gateway.callMapped(Gateway.java:35)
	at tech.xavi.soulsync.gateway.SlskdGateway.getToken(SlskdGateway.java:138)
	at tech.xavi.soulsync.service.auth.AuthService.getSlskdToken(AuthService.java:50)
	at tech.xavi.soulsync.service.task.DownloadService.findStuckDownloads(DownloadService.java:76)
	at tech.xavi.soulsync.service.task.TaskManagerService.runScheduledTask(TaskManagerService.java:58)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:831)
2024-04-16 08:08:25,010        WARN [main] figuration$JpaWebConfiguration: spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2024-04-16 08:08:25,298        INFO [main] web.DefaultSecurityFilterChain: Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@1c58d7be, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@61b8c9de, org.springframework.security.web.context.SecurityContextHolderFilter@2ce47652, org.springframework.security.web.header.HeaderWriterFilter@42d174ad, org.springframework.web.filter.CorsFilter@b34c7c9, org.springframework.security.web.authentication.logout.LogoutFilter@73d91faf, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@2a42019a, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@60194904, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@5b490d5e, org.springframework.security.web.access.ExceptionTranslationFilter@2c1ea7be, org.springframework.security.web.access.intercept.AuthorizationFilter@fde487b]
2024-04-16 08:08:25,520        INFO [main] ache.juli.logging.DirectJDKLog: Starting ProtocolHandler ["http-nio-6743"]
2024-04-16 08:08:25,533        INFO [main] mbedded.tomcat.TomcatWebServer: Tomcat started on port(s): 6743 (http) with context path ''
2024-04-16 08:08:25,544        INFO [main] amework.boot.StartupInfoLogger: Started SoulSyncApplication in 7.338 seconds (process running for 9.566)
2024-04-16 08:08:25,860        INFO [main] nc.service.auth.AccountService: [run] - Default Admin created: 'admin' - 'admin'
2024-04-16 08:08:25,861        INFO [main] i.soulsync.SoulSyncApplication:     ________  __  ____   _____  ___  _______
2024-04-16 08:08:25,861        INFO [main] i.soulsync.SoulSyncApplication:    / __/ __ \/ / / / /  / __| \/ / |/ / ___/
2024-04-16 08:08:25,861        INFO [main] i.soulsync.SoulSyncApplication:   _\ \/ /_/ / /_/ / /___\ \  \  /    / /__ 
2024-04-16 08:08:25,862        INFO [main] i.soulsync.SoulSyncApplication:  /___/\____/\____/____/___/  /_/_/|_/\___/  
2024-04-16 08:08:25,862        INFO [main] i.soulsync.SoulSyncApplication: 
2024-04-16 08:13:24,975        ERROR [scheduling-1] .xavi.soulsync.gateway.Gateway: [ SLSKD | getToken ] - (UnirestException) URL: http://localhost:5030/api/v0/session - An error occurred getting a response from the SLSKD API - Message: org.apache.http.conn.HttpHostConnectException: Connect to localhost:5030 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
com.mashape.unirest.http.exceptions.UnirestException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:5030 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
	at tech.xavi.soulsync.gateway.Gateway.getResponse(Gateway.java:67)
	at tech.xavi.soulsync.gateway.Gateway.call(Gateway.java:55)
	at tech.xavi.soulsync.gateway.Gateway.callMapped(Gateway.java:35)
	at tech.xavi.soulsync.gateway.SlskdGateway.getToken(SlskdGateway.java:138)
	at tech.xavi.soulsync.service.auth.AuthService.getSlskdToken(AuthService.java:50)
	at tech.xavi.soulsync.service.task.DownloadService.findStuckDownloads(DownloadService.java:76)
	at tech.xavi.soulsync.service.task.TaskManagerService.runScheduledTask(TaskManagerService.java:58)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:5030 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
	... 15 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:669)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:331)
	at java.base/java.net.Socket.connect(Socket.java:630)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 26 more
2024-04-16 08:13:24,976        ERROR [scheduling-1] .TaskUtils$LoggingErrorHandler: Unexpected error occurred in scheduled task
tech.xavi.soulsync.configuration.security.SoulSyncException
	at tech.xavi.soulsync.gateway.Gateway.handleUnirestException(Gateway.java:125)
	at tech.xavi.soulsync.gateway.Gateway.call(Gateway.java:57)
	at tech.xavi.soulsync.gateway.Gateway.callMapped(Gateway.java:35)
	at tech.xavi.soulsync.gateway.SlskdGateway.getToken(SlskdGateway.java:138)
	at tech.xavi.soulsync.service.auth.AuthService.getSlskdToken(AuthService.java:50)
	at tech.xavi.soulsync.service.task.DownloadService.findStuckDownloads(DownloadService.java:76)
	at tech.xavi.soulsync.service.task.TaskManagerService.runScheduledTask(TaskManagerService.java:58)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

Frontend logs:
```
 INFO  Accepting connections at http://localhost:7316
 HTTP  4/16/2024 8:08:41 AM 192.168.178.75 GET /
 HTTP  4/16/2024 8:08:41 AM 192.168.178.75 Returned 200 in 55 ms
 HTTP  4/16/2024 8:08:41 AM 192.168.178.75 GET /js/chunk-vendors.dac87fe1.js
 HTTP  4/16/2024 8:08:41 AM 192.168.178.75 Returned 200 in 8 ms
 HTTP  4/16/2024 8:08:41 AM 192.168.178.75 GET /css/chunk-vendors.dcbd1cf6.css
 HTTP  4/16/2024 8:08:41 AM 192.168.178.75 GET /css/app.2c772772.css
 HTTP  4/16/2024 8:08:41 AM 192.168.178.75 GET /js/app.ee861d40.js
 HTTP  4/16/2024 8:08:41 AM 192.168.178.75 Returned 200 in 3 ms
 HTTP  4/16/2024 8:08:41 AM 192.168.178.75 Returned 200 in 4 ms
 HTTP  4/16/2024 8:08:41 AM 192.168.178.75 Returned 200 in 9 ms
 HTTP  4/16/2024 8:08:41 AM 192.168.178.75 GET /fonts/primeicons.ba3f916d.woff2
 HTTP  4/16/2024 8:08:41 AM 192.168.178.75 Returned 200 in 4 ms
 HTTP  4/16/2024 8:08:42 AM 192.168.178.75 GET /favicon.ico
 HTTP  4/16/2024 8:08:42 AM 192.168.178.75 Returned 200 in 4 ms
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 GET /login
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 Returned 200 in 2 ms
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 GET /js/chunk-vendors.dac87fe1.js
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 Returned 304 in 2 ms
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 GET /js/app.ee861d40.js
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 GET /css/chunk-vendors.dcbd1cf6.css
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 GET /css/app.2c772772.css
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 Returned 304 in 4 ms
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 Returned 304 in 4 ms
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 Returned 304 in 4 ms
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 GET /fonts/primeicons.ba3f916d.woff2
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 Returned 304 in 2 ms
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 GET /favicon.ico
 HTTP  4/16/2024 8:09:42 AM 192.168.178.75 Returned 304 in 4 ms
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 GET /
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 Returned 200 in 2 ms
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 GET /js/chunk-vendors.dac87fe1.js
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 Returned 200 in 2 ms
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 GET /css/chunk-vendors.dcbd1cf6.css
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 Returned 200 in 1 ms
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 GET /css/app.2c772772.css
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 GET /js/app.ee861d40.js
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 Returned 200 in 1 ms
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 Returned 200 in 1 ms
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 GET /fonts/primeicons.ba3f916d.woff2
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 Returned 200 in 3 ms
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 GET /favicon.ico
 HTTP  4/16/2024 8:10:43 AM 192.168.178.75 Returned 200 in 3 ms
```
Database logs:

```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
initdb: warning: enabling "trust" authentication for local connections
syncing data to disk ... ok
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2024-04-16 08:08:17.181 UTC [49] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-04-16 08:08:17.187 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-04-16 08:08:17.202 UTC [52] LOG:  database system was shut down at 2024-04-16 08:08:16 UTC
2024-04-16 08:08:17.209 UTC [49] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down....2024-04-16 08:08:17.505 UTC [49] LOG:  received fast shutdown request
2024-04-16 08:08:17.517 UTC [49] LOG:  aborting any active transactions
2024-04-16 08:08:17.521 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
2024-04-16 08:08:17.521 UTC [50] LOG:  shutting down
2024-04-16 08:08:17.523 UTC [50] LOG:  checkpoint starting: shutdown immediate
2024-04-16 08:08:17.704 UTC [50] LOG:  checkpoint complete: wrote 923 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.024 s, sync=0.129 s, total=0.182 s; sync files=301, longest=0.032 s, average=0.001 s; distance=4257 kB, estimate=4257 kB; lsn=0/1913078, redo lsn=0/1913078
2024-04-16 08:08:17.712 UTC [49] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2024-04-16 08:08:17.856 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-04-16 08:08:17.856 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-04-16 08:08:17.856 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-04-16 08:08:17.868 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-04-16 08:08:17.880 UTC [65] LOG:  database system was shut down at 2024-04-16 08:08:17 UTC
2024-04-16 08:08:17.888 UTC [1] LOG:  database system is ready to accept connections
2024-04-16 08:13:17.976 UTC [63] LOG:  checkpoint starting: time
2024-04-16 08:13:28.743 UTC [63] LOG:  checkpoint complete: wrote 110 buffers (0.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=10.742 s, sync=0.015 s, total=10.767 s; sync files=66, longest=0.003 s, average=0.001 s; distance=523 kB, estimate=523 kB; lsn=0/1995D08, redo lsn=0/1995CD0

```

**Comment by xaviqo** [comment]
Hi, sorry for the delay in replying, lately I have a lot of work to do at my job hahaha.

I know the question is very obvious, but it is mandatory. Have you started the SLSKD instance? https://github.com/slskd/slskd

**Comment by thenswan** [comment]
Hey @xaviqo, following up here as I have similar error (managed to sign in, but `SLSKD API` indicator shows that its down). I just ran slskd via docker and then SoulSyncBot (which is great). Re error below - I see that slskd Front End is served on that ip/port -- not sure if SoulSyncBot needs to connect to that.

(slskd is up and configured)

```
2024-05-25 17:56:14,774        ERROR [scheduling-1] .xavi.soulsync.gateway.Gateway: [ SLSKD | getToken ] - (UnirestException) URL: http://localhost:5030/api/v0/session - An error occurred getting a response from the SLSKD API - Message: org.apache.http.conn.HttpHostConnectException: Connect to localhost:5030 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
```
